// <auto-generated />
using System;
using InterfazPFMCFIC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterfazPFMCFIC.Migrations
{
    [DbContext(typeof(DbInterfazPfmcficContext))]
    partial class DbInterfazPfmcficContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficArchivo", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArchivoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoId"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("PesoArchivoKb")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PesoArchivoKB");

                    b.Property<int?>("ProcesoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcesoID");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("RegistroID");

                    b.Property<string>("Ruta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ArchivoId")
                        .HasName("PK__INTERFAZ__3D24276A7FD7C9C3");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("ArchivoId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_ARCHIVO", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCancelacione", b =>
                {
                    b.Property<int>("CancelacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CancelacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancelacionId"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("MotivoCancelacion")
                        .HasColumnType("int");

                    b.Property<int?>("SolictudPfmcficid")
                        .HasColumnType("int")
                        .HasColumnName("SolictudPFMCFICID");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UsuarioID");

                    b.HasKey("CancelacionId")
                        .HasName("PK__INTERFAZ__5A8447EE5E201ADC");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("CancelacionId"), 80);

                    b.HasIndex("SolictudPfmcficid");

                    b.ToTable("INTERFAZ_PFM_CFIC_CANCELACIONES", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCatCodigoRetorno", b =>
                {
                    b.Property<int>("CatCodigoRetornoId")
                        .HasColumnType("int")
                        .HasColumnName("CatCodigoRetornoID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CatCodigoRetornoId");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("CatCodigoRetornoId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_CatCodigoRetorno", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCatEstatusSolicitud", b =>
                {
                    b.Property<int>("CatEstatusSolicitudId")
                        .HasColumnType("int")
                        .HasColumnName("CatEstatusSolicitudID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("CatEstatusSolicitudId");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("CatEstatusSolicitudId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_CatEstatusSolicitud", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCatTipoConfirmacion", b =>
                {
                    b.Property<int>("CatTipoConfirmacionId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoConfirmacionID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CatTipoConfirmacionId");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("CatTipoConfirmacionId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_CatTipoConfirmacion", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCatTipoProducto", b =>
                {
                    b.Property<bool?>("Alias")
                        .HasColumnType("bit");

                    b.Property<bool?>("Archivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("ArmasyExplosivos")
                        .HasColumnType("bit");

                    b.Property<bool?>("BienesInmuebles")
                        .HasColumnType("bit");

                    b.Property<int>("CatTipoProductoId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoProductoID");

                    b.Property<bool?>("CuentasBancarias")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DispositivodeAlmacenamiento")
                        .HasColumnType("bit");

                    b.Property<bool?>("Domicilios")
                        .HasColumnType("bit");

                    b.Property<bool?>("Drogas")
                        .HasColumnType("bit");

                    b.Property<bool?>("EquipoDeComunicacion")
                        .HasColumnType("bit");

                    b.Property<bool?>("EquipoTactico")
                        .HasColumnType("bit");

                    b.Property<bool?>("Eventos")
                        .HasColumnType("bit");

                    b.Property<bool?>("Expediente")
                        .HasColumnType("bit");

                    b.Property<bool?>("FaunaProtegida")
                        .HasColumnType("bit");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("InternetuOtros")
                        .HasColumnType("bit");

                    b.Property<bool?>("MaterialApocrifo")
                        .HasColumnType("bit");

                    b.Property<bool?>("Numeral")
                        .HasColumnType("bit");

                    b.Property<bool?>("OrganizacionesDelictivas")
                        .HasColumnType("bit");

                    b.Property<bool?>("Otros")
                        .HasColumnType("bit");

                    b.Property<bool?>("Personas")
                        .HasColumnType("bit");

                    b.Property<bool?>("PersonasMorales")
                        .HasColumnType("bit");

                    b.Property<bool>("Pfmcfic")
                        .HasColumnType("bit")
                        .HasColumnName("PFMCFIC");

                    b.Property<bool?>("Ubicacion")
                        .HasColumnType("bit");

                    b.Property<bool?>("Vehículos")
                        .HasColumnType("bit");

                    b.ToTable("INTERFAZ_PFM_CFIC_CatTipoProducto", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficConfirmacionEnvio", b =>
                {
                    b.Property<int>("ConfirmacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfirmacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfirmacionId"));

                    b.Property<int?>("CodigoRetorno")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<long?>("FolioConfirmacionCfic")
                        .HasColumnType("bigint")
                        .HasColumnName("FolioConfirmacionCFIC");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("SolictudPfmcficid")
                        .HasColumnType("int")
                        .HasColumnName("SolictudPFMCFICID");

                    b.Property<int?>("TipoConfirmacion")
                        .HasColumnType("int");

                    b.HasKey("ConfirmacionId")
                        .HasName("PK__INTERFAZ__637503903EAD6EE9");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("ConfirmacionId"), 80);

                    b.HasIndex("SolictudPfmcficid");

                    b.ToTable("INTERFAZ_PFM_CFIC_CONFIRMACION_ENVIO", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficPlantilla", b =>
                {
                    b.Property<int>("PlantillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlantillaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaId"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<int?>("CatTipoProductoId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoProductoID");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ruta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UsuarioID");

                    b.HasKey("PlantillaId")
                        .HasName("PK__INTERFAZ__C5DEB58C9A287233");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("PlantillaId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_PLANTILLAS", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficProductorecibido", b =>
                {
                    b.Property<int>("ProductoRecibidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoRecibidoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoRecibidoId"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaProducto")
                        .HasColumnType("datetime");

                    b.Property<int>("GeneralesAntecedentesId")
                        .HasColumnType("int")
                        .HasColumnName("GeneralesAntecedentesID");

                    b.Property<int>("SolicitudPfmcficid")
                        .HasColumnType("int")
                        .HasColumnName("SolicitudPFMCFICID");

                    b.Property<short?>("TipoProducto")
                        .HasColumnType("smallint");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ProductoRecibidoId");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("ProductoRecibidoId"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_PRODUCTORECIBIDO", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficRechazo", b =>
                {
                    b.Property<int>("RechazoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RechazoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RechazoId"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool?>("Expirado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<int?>("MotivoRechazoId")
                        .HasColumnType("int")
                        .HasColumnName("MotivoRechazoID");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("SolictudPfmcficid")
                        .HasColumnType("int")
                        .HasColumnName("SolictudPFMCFICID");

                    b.Property<int?>("TipoRechazoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoRechazoID");

                    b.HasKey("RechazoId")
                        .HasName("PK__INTERFAZ__EEE56439E97E3F10");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("RechazoId"), 80);

                    b.HasIndex("SolictudPfmcficid");

                    b.ToTable("INTERFAZ_PFM_CFIC_RECHAZOS", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", b =>
                {
                    b.Property<int>("SolicitudPfmcficid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SolicitudPFMCFICID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudPfmcficid"));

                    b.Property<int?>("ActosApfmid")
                        .HasColumnType("int")
                        .HasColumnName("ActosAPFMID");

                    b.Property<int?>("AdscripcionId")
                        .HasColumnType("int")
                        .HasColumnName("AdscripcionID");

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<int?>("CatEstatusSolicitudId")
                        .HasColumnType("int")
                        .HasColumnName("CatEstatusSolicitudID");

                    b.Property<int?>("CatTipoEnvioId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoEnvioID");

                    b.Property<int?>("CatTipoMandamientoId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoMandamientoID");

                    b.Property<int?>("CatTipoProductoId")
                        .HasColumnType("int")
                        .HasColumnName("CatTipoProductoID");

                    b.Property<bool?>("ConDetenido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaAltaDelta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaOficio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaSistema")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("datetime");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Oficio")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("PersonalID");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UsuarioID");

                    b.HasKey("SolicitudPfmcficid")
                        .HasName("PK__INTERFAZ__3411BB0B5B5A8B25");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("SolicitudPfmcficid"), 80);

                    b.ToTable("INTERFAZ_PFM_CFIC_SOLICITUD", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmPfmCficConfirmacionRecepcion", b =>
                {
                    b.Property<int>("ConfirmacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfirmacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfirmacionId"));

                    b.Property<int?>("CodigoRetorno")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<long?>("FolioConfirmacionPfm")
                        .HasColumnType("bigint")
                        .HasColumnName("FolioConfirmacionPFM");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("RegistroID");

                    b.Property<int?>("SolictudPfmcficid")
                        .HasColumnType("int")
                        .HasColumnName("SolictudPFMCFICID");

                    b.Property<int?>("TipoConfirmacion")
                        .HasColumnType("int");

                    b.HasKey("ConfirmacionId")
                        .HasName("PK__INTERFAZ__6375039090C53A46");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("ConfirmacionId"), 80);

                    b.HasIndex("SolictudPfmcficid");

                    b.ToTable("INTERFAZ_PFM_PFM_CFIC_CONFIRMACION_RECEPCION", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.MotivoRechazo", b =>
                {
                    b.Property<int>("MotivoRechazoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotivoRechazoId"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cenapi")
                        .HasColumnType("bit")
                        .HasColumnName("CENAPI");

                    b.Property<bool?>("Cgsp")
                        .HasColumnType("bit")
                        .HasColumnName("CGSP");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Pfm")
                        .HasColumnType("bit")
                        .HasColumnName("PFM");

                    b.Property<int>("TipoRechazo")
                        .HasColumnType("int");

                    b.HasKey("MotivoRechazoId")
                        .HasName("PK_dbo.MotivoRechazoNueva");

                    b.ToTable("MotivoRechazo", (string)null);
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficCancelacione", b =>
                {
                    b.HasOne("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", "SolictudPfmcfic")
                        .WithMany("InterfazPfmCficCancelaciones")
                        .HasForeignKey("SolictudPfmcficid")
                        .HasConstraintName("FK_INTERFAZ_PFM_CFIC_CANCELACIONES_INTERFAZ_PFM_CFIC_SOLICITUD");

                    b.Navigation("SolictudPfmcfic");
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficConfirmacionEnvio", b =>
                {
                    b.HasOne("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", "SolictudPfmcfic")
                        .WithMany("InterfazPfmCficConfirmacionEnvios")
                        .HasForeignKey("SolictudPfmcficid")
                        .HasConstraintName("FK_INTERFAZ_PFM_CFIC_CONFIRMACION_ENVIO_INTERFAZ_PFM_CFIC_SOLICITUD");

                    b.Navigation("SolictudPfmcfic");
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficRechazo", b =>
                {
                    b.HasOne("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", "SolictudPfmcfic")
                        .WithMany("InterfazPfmCficRechazos")
                        .HasForeignKey("SolictudPfmcficid")
                        .HasConstraintName("FK_INTERFAZ_PFM_CFIC_RECHAZOS_INTERFAZ_PFM_CFIC_SOLICITUD");

                    b.Navigation("SolictudPfmcfic");
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmPfmCficConfirmacionRecepcion", b =>
                {
                    b.HasOne("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", "SolictudPfmcfic")
                        .WithMany("InterfazPfmPfmCficConfirmacionRecepcions")
                        .HasForeignKey("SolictudPfmcficid")
                        .HasConstraintName("FK_INTERFAZ_PFM_PFM_CFIC_CONFIRMACION_RECEPCION_INTERFAZ_PFM_CFIC_SOLICITUD");

                    b.Navigation("SolictudPfmcfic");
                });

            modelBuilder.Entity("InterfazPFMCFIC.Models.InterfazPfmCficSolicitud", b =>
                {
                    b.Navigation("InterfazPfmCficCancelaciones");

                    b.Navigation("InterfazPfmCficConfirmacionEnvios");

                    b.Navigation("InterfazPfmCficRechazos");

                    b.Navigation("InterfazPfmPfmCficConfirmacionRecepcions");
                });
#pragma warning restore 612, 618
        }
    }
}
